### ISSUE TITLE
how are we dealing with parallelization

### ISSUE THREAD

**Issue by berndbischl** [mlr-org/mlr3hyperband#20]
its unfortunate that in later bracket stages we have less and less configs to eval. 
what do we do about this?

**Comment by SebGruber1996** [comment]
Since the last stage of a bracket always requires the previous stage to be fully evaluated, I don't see a way to parallelize the inner loop (bracket stages). Only the outer loop seems to be extendable in an easy way for that, but only as long as we don't use the information of previous brackets for sampling new configurations.

A possible solution for this is basically something Martin brought up a while ago (even though for different reasons) and would be to adjust the algorithm with a hyperparameter that changes the number of configurations in the every last bracket stage. Currently, most of the time we have only one configuration for maximum budget evaluation, but if we had several more in the last bracket stage, we can parallelize those.

**Comment by juliambr** [comment]
Also this is stated in the outlook section of the original hyperband paper, and is a research question.

**Comment by be-marc** [comment]
> its unfortunate that in later bracket stages we have less and less configs to eval

We solved this with the hyperbandX algorithm which evaluates stages of equal budget in parallel.
